apiVersion: v1
kind: ConfigMap
metadata:
  name: nephio-webui-config
  namespace: nephio-webui
data:
  app-config.nephio.yaml: |
    app:
      baseUrl: http://localhost:7007

    # Backstage backend configuration
    backend:
      # Note that the baseUrl should be the URL that the browser and other clients
      # should use when communicating with the backend, i.e. it needs to be
      # reachable not just from within the backend host, but from all of your
      # callers. When its value is "http://localhost:7007", it's strictly private
      # and can't be reached by others.
      baseUrl: http://localhost:7007

      listen:
        port: 7007

      # Content Security Policy
      csp:
        # Allows images to be pulled from GitHub and Nephio
        img-src: ["'self'", 'data:', 'https://raw.githubusercontent.com']
        upgrade-insecure-requests: false

    auth:
      # see https://backstage.io/docs/auth/ to learn about auth providers
      providers:
        google:
          development:
            clientId: ${AUTH_GOOGLE_CLIENT_ID}
            clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
        okta:
          development:
            clientId: ${AUTH_OKTA_CLIENT_ID}
            clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
            audience: ${AUTH_OKTA_AUDIENCE}
            authServerId: ${AUTH_OKTA_AUTH_SERVER_ID}
            idp: ${AUTH_OKTA_IDP}

    # Config as Data Plugin configuration
    configAsData:
      # The namespace where Porch managed resources live.
      resourcesNamespace: default

      # Do not use Config Sync
      gitOpsDeliveryTool: none

      # Management cluster configuration
      clusterLocatorMethod:
        authProvider: ${AUTH_PROVIDER}

        # For authProvider: oidc
        oidcTokenProvider: ${AUTH_OIDC_TOKEN_PROVIDER}

        # For authProvider: service-account
        serviceAccountToken: ${AUTH_SERVICE_ACCOUNT_TOKEN}

      # Nephio branding customizations
      branding:
        title: Nephio
        header:
          logoUrl: https://raw.githubusercontent.com/nephio-project/kpt-backstage-plugins/v1.0.1/packages/app/public/nephio_logo_colorwhite_horizontal.svg
          backgroundImageUrl: https://raw.githubusercontent.com/nephio-project/kpt-backstage-plugins/v1.0.1/packages/app/public/nephio-background.png
