apiVersion: apps/v1
kind: Deployment
metadata:
  name: nephio-webui
  namespace: nephio-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nephio-webui
  template:
    metadata:
      labels:
        app: nephio-webui
    spec:
      serviceAccountName: nephio-webui-sa
      terminationGracePeriodSeconds: 10
      containers:
      - name: main
        image: nephio/kpt-backstage-plugins:v2.0.0
        imagePullPolicy: IfNotPresent
        args:
        - --config
        - /etc/config/app-config.nephio.yaml
        ports:
        - name: http
          containerPort: 7007
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        readinessProbe:
          httpGet:
            path: /
            port: 7007
        env:
        - name: AUTH_PROVIDER
          value: current-context
        - name: AUTH_OIDC_TOKEN_PROVIDER
          value: okta
      volumes:
      - name: config-volume
        configMap:
          name: nephio-webui-config
