---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ue-configmap
  labels:
    app.kubernetes.io/version: "v3.2.6"
    app: ueransim
    component: ue
data:
  ue-config.yaml: |
    supi: "imsi-208930000000003"  # IMSI number
    mcc: '208' # Mobile Country Code value
    mnc: '93' # Mobile Network Code value (2 or 3 digits)
    key: "8baf473f2f8fd09487cccbd7097c6862" # Operator code (OP or OPC) of the UE
    op: "8e27b6af0e692e750f32667a3b14605d" # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: "OPC" # This value specifies the OP type and it can be either 'OP' or 'OPC'
    amf: '8000' # Authentication Management Field (AMF) value
    imei: '356938035643803' # IMEI number of the device
    imeiSv: '4370816125816151'
    # UAC Access Identities Configuration
    uacAic:
      mps: false
      mcs: false
    # UAC Access Control Class
    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false
    sessions:
      - type: "IPv4"
        apn: "internet"
        slice:
          sst: 0x01
          sd: 0x010203
    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: 0x01
        sd: 0x010203
    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        sd: 1
    # Supported encryption and integrity algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true
    ciphering:
      EA1: true
      EA2: true
      EA3: true
    # Integrity protection maximum data rate for user plane
    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'
    
    # List of gNB IP addresses for Radio Link Simulation
    gnbSearchList:
      - gnb-service

  wrapper.sh: |
    #!/bin/bash

    mkdir /dev/net
    mknod /dev/net/tun c 10 200

    ./nr-ue -c ../config/ue-config.yaml
